import Link from "next/link";
import Image from "next/image";
import { ukPassportFaqs } from "@/lib/uk-passport-content";
import "./uk-guide.css";

export function UKPassportIntro() {
  return <header className="uk-guide uk-guide-intro">
    <nav aria-label="Breadcrumb"><Link href="/">Home</Link> / <Link href="/passport-photos">Passport photo guides</Link> / United Kingdom</nav>
    <div className="uk-guide-hero"><div><p className="uk-guide-kicker">PIXPASSVISA · UK PASSPORT PHOTO GUIDE</p><h1>UK passport photo size: printed and digital requirements</h1><p>A printed British passport picture measures <strong>35 × 45 mm (3.5 × 4.5 cm)</strong>. Applying online? Digital photos have separate pixel and file-size rules, and your original photo should not be cropped before submission.</p><p className="uk-guide-review">Requirements checked against GOV.UK on 6 October 2026.</p><a href="#uk-photo-size" className="uk-guide-button">Compare the photo formats ↓</a></div><Image src="/images/uk-passport-photo-size-guide.svg" width={720} height={600} priority alt="PixPassVisa UK passport size guide: printed photos 35 by 45 mm, crown-to-chin height 29–34 mm; digital minimum dimensions 600 by 750 pixels" /></div>
  </header>;
}

export default function UKPassportGuide() {
  return <article className="uk-guide uk-guide-article">
    <section id="uk-photo-size"><p className="uk-guide-kicker">CHOOSE YOUR APPLICATION ROUTE</p><h2>UK passport photo measurements at a glance</h2><div className="uk-guide-table-wrap"><table><caption>Printed photo dimensions and digital upload specifications</caption><thead><tr><th scope="col">Requirement</th><th scope="col">Printed passport photo</th><th scope="col">Digital passport photo</th></tr></thead><tbody><tr><th scope="row">Size</th><td>35 mm wide × 45 mm high</td><td>At least 600 px wide × 750 px high</td></tr><tr><th scope="row">In centimetres</th><td>3.5 cm × 4.5 cm</td><td>Use pixel dimensions, not centimetres</td></tr><tr><th scope="row">Framing</th><td>29–34 mm from crown to chin</td><td>Own-device photo: include head, shoulders and upper body</td></tr><tr><th scope="row">File or copies</th><td>Two identical printed photographs</td><td>50 KB–10 MB</td></tr><tr><th scope="row">Editing</th><td>Unaltered by computer software</td><td>Unaltered; do not crop your own-device photo</td></tr></tbody></table></div><p className="uk-guide-sources">Sources: <a href="https://www.gov.uk/photos-for-passports/photo-requirements">GOV.UK printed photo rules</a> · <a href="https://www.gov.uk/photos-for-passports">GOV.UK digital photo rules</a>.</p></section>
    <section><h2>Printed passport photos: check the finished size</h2><p>The 7:9 frame describes the printed format. A photo file can look correctly proportioned on screen and still print at the wrong physical size. If you prepare a sheet, avoid fit-to-page scaling and measure the finished photograph with a ruler. Follow the authority’s paper and print-quality instructions; a downloadable template alone does not certify a print.</p><Link href="/passport-photo-print-template-generator">Explore photo print templates →</Link></section>
    <section className="uk-guide-callout"><h2>Applying online? Keep your original photograph</h2><p>Do not turn the printed 35 × 45 mm specification into an automatic crop for an online passport application. Use a genuine recent photograph and follow the official upload process. This page’s processing controls cannot turn an altered image into an unaltered original.</p><p>A photo code from a participating booth or shop is also different from a JPEG download. PixPassVisa does not issue an HMPO photo code.</p><a href="https://www.gov.uk/photos-for-passports">Read the official online application photo guidance ↗</a></section>
    <section><h2>How to take a clearer passport photo at home</h2><ol><li>Ask someone to hold the camera at eye level, with room around your head and shoulders.</li><li>Use even light and a plain background. Review the original for blur, shadows and glare.</li><li>Avoid face filters, beauty effects and background replacement. Retake a poor photograph rather than trying to repair your appearance.</li><li>Check the instructions for your application before uploading or printing.</li></ol><p>For babies, children, accessibility needs and permitted head coverings, consult the specific exceptions in the official guidance.</p><Link href="/uk-passport-photo-checker-online-free">Review the UK passport photo checklist →</Link></section>
    <section><h2>Passport, driving licence and travel pass photos are different tasks</h2><p>A passport guide cannot establish the correct format for every UK identity document. Driving licences, Oyster photocards, railcards and local passes use their issuers’ own rules. Confirm the process with the issuer, including whether it reuses an existing photo, accepts a new upload or asks for a physical print.</p><p>For more guidance, visit our <Link href="/uk">UK photo guide hub</Link>, <Link href="/passport-photo-sizes">passport photo size chart</Link> or <Link href="/passport-photo-video">photo preparation video</Link>.</p></section>
    <section aria-labelledby="uk-photo-faq"><h2 id="uk-photo-faq">UK passport photo size questions</h2>{ukPassportFaqs.map(({q,a})=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <aside className="uk-guide-note">PixPassVisa is an independent photo preparation service, not HM Passport Office or DVLA. Measurements and checks help you review a photograph; the issuing authority decides acceptance.</aside>
  </article>;
}
