export const homeFaqs = [
  { q: "How can I make a passport photo online?", a: "Start with a recent, genuine portrait. Select your country and document, upload the photo, and review the crop and automated checks. Preview the output and price before purchasing a digital photo and print sheet." },
  { q: "Are passport and visa photo requirements the same?", a: "Not always. The same country may have different requirements for passports, visas, and other documents. Select the exact application and check the issuing authority's current instructions, including digital upload limits." },
  { q: "Can I take a passport photo with my phone?", a: "A phone can capture a suitable starting photo if the image is sharp, well lit, and taken straight on. Ask someone to take the picture at eye level, leave room for cropping, and avoid filters. Check your authority's capture rules before submitting." },
  { q: "How do I print a passport photo at the correct size?", a: "Use the required photo dimensions and print the sheet at actual size, without fit-to-page scaling. Measure the finished photos with a ruler and check the authority's paper and print-quality rules. A print sheet does not itself guarantee a compliant physical print." },
  { q: "Can I check my passport photo for free?", a: "Yes. The automated photo checker is free to use. Creating a downloadable processed photo and print sheet is a separate paid service. Preview your result and review the price before paying." },
  { q: "Which passport photo size should I choose?", a: "Choose the country and the exact document you are applying for. Printed dimensions, digital pixel dimensions, and upload file limits are different requirements. Check the authority's instructions for your application before choosing a format." },
  { q: "Does passing the checker guarantee acceptance?", a: "No. Automated checks help identify common problems, but they cannot certify a photo or guarantee acceptance. The issuing authority makes the final decision. pixpassvisa.com is an independent service, not a government agency." },
  { q: "Can I use an AI-generated or digitally retouched face?", a: "No. Use a recent, genuine photograph of yourself without face filters or retouching. Some authorities also prohibit background replacement or other software alterations. Review the original photo and your authority's editing rules before submitting." },
  { q: "Do I need an app or a subscription?", a: "The tools run in your browser on a phone or computer. Paid photo downloads use a one-time payment. Review the selected document, output, and local price in the preview before checkout." },
  { q: "How are uploaded photos handled?", a: "Photo processing can involve our servers and storage providers. Read the privacy policy and data security page for storage, retention, and deletion details. Contact support if you need help with a photo or deletion request." },
];
